Repository snapshot-labs/sx-monorepo, pull requests merged in 2024-04, with the labels that each got.

#228 feat(ux): sort proposals results by weight
  apps/ui/src/components/ProposalResults.vue
Labels: area: UI

#223 fix(ui): fix shutter message appearing in proposals list
  apps/ui/src/components/ProposalResults.vue
Labels: area: UI

#220 fix: fix error when auto logging with locked metamask
  apps/ui/src/composables/useWeb3.ts
Labels: bug, area: UI

#188 feat(ux): add chars count to input with maxLength
  apps/ui/src/components/Ui/InputString.vue
  apps/ui/src/components/Ui/WrapperInput.vue
  apps/ui/src/style.scss
Labels: enhancement, area: UI

#209 feat: show info message if Herodotus voting power is not available yet on a proposal
  .changeset/calm-pens-leave.md
  .changeset/sixty-otters-judge.md
  apps/api/src/overrrides.ts
  apps/mana/src/stark/herodotus.ts
  apps/ui/src/views/Proposal.vue
  packages/sx.js/src/clients/starknet/herodotus/index.ts
  packages/sx.js/src/strategies/starknet/evmSlotValue.ts
  packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts
  packages/sx.js/src/strategies/starknet/utils.ts
  packages/sx.js/src/utils/errors.ts
  packages/sx.js/src/utils/index.ts
Labels: area: UI, area: SDK

#196 feat: add AI text to speech
  apps/ui/src/composables/useAi.ts
  apps/ui/src/composables/useAudio.ts
  apps/ui/src/views/Proposal/Overview.vue
Labels: enhancement, area: UI

#187 chore: update axiom strategy address
  apps/subgraph-api/abis/AxiomExecutionStrategy.json
  apps/subgraph-api/src/mapping.ts
  packages/sx.js/src/clients/evm/ethereum-tx/abis/AxiomExecutionStrategy.json
  packages/sx.js/src/evmNetworks.ts
Labels: area: SDK, area: API
