Repository snapshot-labs/sx-monorepo, pull requests merged in 2024-03, with the labels that each got.

#172 fix: fix invalid decimal voting power
  .changeset/five-gifts-rest.md
  apps/ui/src/networks/offchain/actions.ts
  packages/sx.js/src/strategies/offchain/remote-vp.ts
Labels: bug, area: UI

#170 refactor: move tooltip library to vueTippy
  apps/ui/package.json
  apps/ui/src/components/Ui/Tooltip.vue
  apps/ui/src/main.ts
  apps/ui/src/style.scss
  yarn.lock
Labels: area: UI

#189 fix(ux): do not save empty proposals in draft
  apps/ui/src/composables/useEditor.ts
Labels: bug, area: UI

#173 feat: resolve proposal author address to domain name
  apps/ui/src/components/ProposalsListItem.vue
  apps/ui/src/components/TransactionsListItem.vue
  apps/ui/src/helpers/stamp.ts
  apps/ui/src/stores/proposals.ts
  apps/ui/src/types.ts
  apps/ui/src/views/Proposal/Overview.vue
Labels: enhancement, area: UI

#165 fix: avoid voting power computation for starknet account on snapshot spaces
  apps/ui/src/networks/offchain/actions.ts
  apps/ui/src/networks/offchain/index.test.ts
Labels: enhancement, area: UI

#193 feat: show proposal's AI summary
  apps/ui/src/views/Proposal/Overview.vue
Labels: enhancement, area: UI

#203 test: add subgraph tests via matchstick-as
  apps/subgraph-api/.gitignore
  apps/subgraph-api/package.json
  apps/subgraph-api/src/helpers.ts
  apps/subgraph-api/tests/helpers.test.ts
  package.json
  yarn.lock
Labels: area: API

#192 feat: only load votes per-space
  apps/ui/src/App.vue
  apps/ui/src/composables/useAccount.ts
  apps/ui/src/networks/common/graphqlApi/index.ts
  apps/ui/src/networks/common/graphqlApi/queries.ts
  apps/ui/src/networks/offchain/api/index.ts
  apps/ui/src/networks/offchain/api/queries.ts
  apps/ui/src/networks/types.ts
  apps/ui/src/views/Proposal.vue
  apps/ui/src/views/Space.vue
Labels: area: UI

#175 feat: allow creation of offchain proposals with weighted and quadratic voting type
  .changeset/smart-walls-chew.md
  apps/ui/src/components/EditorVotingType.vue
  apps/ui/src/components/ProposalVoteWeighted.vue
  apps/ui/src/helpers/constants.ts
  apps/ui/src/helpers/utils.ts
  apps/ui/src/networks/offchain/api/types.ts
  apps/ui/src/networks/offchain/constants.ts
  apps/ui/src/networks/offchain/helpers.ts
  apps/ui/src/style.scss
  apps/ui/src/types.ts
  apps/ui/src/views/Proposal.vue
  apps/ui/src/views/Proposal/Votes.vue
  packages/sx.js/src/clients/offchain/ethereum-sig/index.ts
  packages/sx.js/src/clients/offchain/ethereum-sig/types.ts
  packages/sx.js/src/clients/offchain/types.ts
  packages/sx.js/src/clients/offchain/utils.ts
Labels: enhancement, area: UI, area: SDK

#225 fix(ui): use same results style for all vote type
  apps/ui/src/components/ProposalResults.vue
  apps/ui/src/style.scss
Labels: area: UI
